curl -O https://storage.googleapis.com/occrp-data-exports/us_cia_world_leaders/us_cia_world_leaders.json
curl -O https://storage.googleapis.com/occrp-data-exports/everypolitician/everypolitician.json
curl -O https://storage.googleapis.com/occrp-data-exports/eu_meps/eu_meps.json
curl -O https://storage.googleapis.com/occrp-data-exports/un_sc_sanctions/un_sc_sanctions.json
curl -O https://storage.googleapis.com/occrp-data-exports/ch_seco_sanctions/ch_seco_sanctions.json
curl -O https://storage.googleapis.com/occrp-data-exports/us_ofac/us_ofac.json
curl -O https://storage.googleapis.com/occrp-data-exports/us_bis_denied/us_bis_denied.json
curl -O https://storage.googleapis.com/occrp-data-exports/gb_hmt_sanctions/gb_hmt_sanctions.json
curl -O https://storage.googleapis.com/occrp-data-exports/eu_eeas_sanctions/eu_eeas_sanctions.json
curl -O https://storage.googleapis.com/occrp-data-exports/au_dfat_sanctions/au_dfat_sanctions.json
curl -O https://storage.googleapis.com/occrp-data-exports/ca_dfatd_sema_sanctions/ca_dfatd_sema_sanctions.json